### ISSUE TITLE
Localization difference

### ISSUE THREAD

**Issue by yijing2050** [SiyuanHuang95/Livox-Localization#1]
Hello,I have a question that the LIO_Livox has given the position so what are the differences between your Localization and theirs?or what are the advantages over theirs.Thanks.

**Comment by SiyuanHuang95** [comment]
Hi, @yijing2050  thanks for your interest in our work.

There are no great common parts with LIO_Livox, which is only a pure odometry framework. 

In this work, we use Fast-Lio as our odometry block and use the pre-built point-cloud map to eliminate the accumulated odometry errors with scan2map matching as [Code Here](https://github.com/SiyuanHuang95/Livox-Localization/blob/aa200def388dec326c739ec6a98fe892fe0cb99a/scripts/global_localization.py#L125).  Besides, we add loop-closure and initialization with ScanContext, as described in our Readme.

For any further questions, we are happy to give detailed infos.

also, there is one extension part for LIO_Livox, you can find here: https://github.com/PJLab-ADG/Livox-Mapping

**Comment by yijing2050** [comment]
Hello,there is a little bug,when I catkin_make the src of Livox-Mapping and Livox-Localization and so on, a fatal error comes up:fast_lio/Pose6D.h,no such files or directory .So I check and think twice of the prerequisites of  FAST-LIO, then I copy the Pose6D.h from the ~/devel/include/ livox_localiztion to the ~/devel/include/fast_lio/, the fast_lio folder is added by me.Finally , it succeed. But I don't know whether it is right. Looking forward to your reply.

**Comment by yijing2050** [comment]
Hello,there is a little bug,when I catkin_make the src of Livox-Mapping and Livox-Localization and so on, a fatal error comes up:fast_lio/Pose6D.h,no such files or directory .So I check and think twice of the prerequisites of  FAST-LIO, then I copy the Pose6D.h from the ~/devel/include/ livox_localiztion to the ~/devel/include/fast_lio/, the fast_lio folder is added by me.Finally , it succeed. But I don't know whether it is right. Looking forward to your reply.

**Comment by SiyuanHuang95** [comment]
Hi, @yijing2050 

Thanks for your interest in our work. 

That is not a so-called bug for the miss of Pose6D.h, it is the problem of ROS-Message generation issue. That header should be generated with the msg/Pose6D.msg, however, the message generation process is not always ideal like we thought, like [tutorial](https://www.theconstructsim.com/ros-qa-163-custom-message-fails-build-no-file-directory/). So, maybe try **catkin_make** more times, the issue will be fixed! (ROS is not always smart enough :) ) But, if you already have Pose6D.h generated, in Livox_Localization or Fast-LIO, just copy it! They should be the same!


Bests,

**Comment by SiyuanHuang95** [comment]
Also, your newer issue is not related to the original topic. I would suggest opening a new issue next time.

Bests

**Comment by SiyuanHuang95** [comment]
Since there is no update recently, I would close this issue.
