### ISSUE TITLE
what's the difference between  FAST-LIO-LOCALIZATION and this project

### ISSUE THREAD

**Issue by InterKnight** [SiyuanHuang95/Livox-Localization#10]
Hi, Thank you for this great job. 

I‘m new to SLAM, so am I right in understanding that ：the  difference between  FAST-LIO-LOCALIZATION and this project is that this project don't need set inital pose manually？

thank you very much！

**Comment by SiyuanHuang95** [comment]
Thanks for your interest in our work. :)

You are almost right.

We use ScanContext to do the init part, so we have some ScanContext-related files inside. You can have a kind check when you need it.

**Comment by InterKnight** [comment]
Thank you very much ! great project
