### ISSUE TITLE
Localisation in Dynamic Environments

### ISSUE THREAD

**Issue by hardesh-peppermint** [SiyuanHuang95/Livox-Localization#11]
Hi,
Thanks for sharing this project with the open-source community. 
I had a question regarding localization in a dynamic environment. Have you had the chance to test this out dynamic environments such as factories and warehouses over time? If yes how was the performance of the solution? 

TIA

**Comment by SiyuanHuang95** [comment]
1. I haven't tested this framework in a dynamic environment.
2. My prior experience is that:
- when the ration of dynamic objects is reasonable, just filter them out, the performance is still acceptable;
- when ration is huge,it is much challenging

**Comment by hardesh-peppermint** [comment]
Hi,
Thanks for the reply. This was helpful. 
Have you seen any papers that consider deployment of the SLAM solution in dynamic environment?

**Comment by SiyuanHuang95** [comment]
Hi,

just google "Dynamic Environment && SLAM", you will get plenty of papers.

Dynamic object tracking for slam is an example

**Comment by hardesh-peppermint** [comment]
Hi,
Thanks for the reply. 

I've seen some papers that use object detection using a camera and then remove dynamic objects from the PCL. Some direct pointcloud-based approaches use some kind of clustering to remove the dynamic objects. 

Closing the issue.

**Comment by SiyuanHuang95** [comment]
Right. You can also check our Mapping Module: https://github.com/PJLab-ADG/Livox-Mapping, where we use one camera for object removing in post-processing.  Hope it could help you.
