### ISSUE TITLE
Is it useful for global localization without moving from start-up?

### ISSUE THREAD

**Issue by valenbase** [SiyuanHuang95/Livox-Localization#12]
same as the title

**Comment by SiyuanHuang95** [comment]
sorry, but I cannot catch your idea. :-(

Do you mean that we should stay for seconds before global localization is done?

**Comment by valenbase** [comment]
@SiyuanHuang95 yes!

**Comment by SiyuanHuang95** [comment]
If the stay is waiting for the initialization of hardware, then yes.

Others, I am afraid now. To get a better global localization, letting the robot wander a litter would be a good choice which would help to avoid getting stuck in some featureless place. And one common choice for industrial usage would be using registration between the local map and the global map.

**Comment by valenbase** [comment]
@SiyuanHuang95 OK,thanks
