### ISSUE TITLE
关于*.odom文件是如何生成的

### ISSUE THREAD

**Issue by zhangxuanxuan71** [SiyuanHuang95/Livox-Localization#13]
您好，打扰了，请问*.odom文件是如何生成的？我运行了livox_mapping只生成了.pcd文件和位姿的txt文件。谢谢您，打扰了

**Comment by SiyuanHuang95** [comment]
你好，感谢对该项目的兴趣.

odom文件其实就是txt文件的另一种表达，你可以自己写一个简单的python脚本进行转换。

odom主要是为了和interactive_slam进行对齐；

或者你可以考虑把livox_localization中的odom替换为txt，本质一样的

**Comment by zhangxuanxuan71** [comment]
明白了，谢谢您的解答

**Comment by zhangxuanxuan71** [comment]
您好，我在确认一下，odom格式就是时间戳+位置（x、y、z）+姿态四元数，是么？

**Comment by SiyuanHuang95** [comment]
你好，可以参考我们的载入代码：    def livox_load_odom_pose(pose_file)，详见[code](https://github.com/SiyuanHuang95/Livox-Localization/blob/aa200def388dec326c739ec6a98fe892fe0cb99a/scripts/scan_context_manager.py#L107)，里面只有一个SE3

**Comment by SiyuanHuang95** [comment]
你好，可以参考我们的载入代码：    def livox_load_odom_pose(pose_file)，详见[code](https://github.com/SiyuanHuang95/Livox-Localization/blob/aa200def388dec326c739ec6a98fe892fe0cb99a/scripts/scan_context_manager.py#L107)，里面只有一个SE3

**Comment by zhangxuanxuan71** [comment]
明白了，谢谢

**Comment by zhangxuanxuan71** [comment]
您好，按照您readme文件中的说明，roslaunch之后出现了红字“[global_localization-2] process has died [pid 19784, exit code 1”，是什么原因么？

**Comment by giangdao1402** [comment]
@zhangxuanxuan71 
Hey how can you generate .odom files. Can you give me instruction
