### ISSUE TITLE
Why the odom of relocation drift?

### ISSUE THREAD

**Issue by greatplan2017** [SiyuanHuang95/Livox-Localization#3]
![relocation](https://user-images.githubusercontent.com/33953220/157857380-abea07ab-ce1d-446e-be16-71a854f6cd35.png)

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest,

1. You are testing it with your own dataset? 
2. The lidar point cloud map is obtained with also Livox?
3. Did it initialize successfully?


Bests,

**Comment by greatplan2017** [comment]
1. yes, i am testing my dataset.
2. My dataset was obtained with Livox Mid-100
3. how could i know initialize successfully?

**Comment by SiyuanHuang95** [comment]
1. Our framework is designed for an industrial park, some specific
modification is made.
2. Have not tested with Mid-100, maybe the points pattern have some
differences.
3. You can check it with the same rosbag for mapping and localization
module, and see whether localization can be aligned with your prior
knowledge.


Bests,

greatplan2017 ***@***.***> 于2022年3月14日周一 10:39写道：

**Comment by greatplan2017** [comment]
Thanks, I have solved the problems.

**Comment by SiyuanHuang95** [comment]
Cool! Glad to hear your success.

Could you share some hints about how to solve these problems?

Bests

**Comment by greatplan2017** [comment]
The function crop_global_map_in_FOV under my dataset and device(mid-100) is unstable.

Thanks.

**Comment by SiyuanHuang95** [comment]
Hi,

you may need to modify the FOV parameter for mid-100.

**Comment by SiyuanHuang95** [comment]
Since no update now, I will close this issue
