### ISSUE TITLE
why is it  waiting for global map? and didn't proceed forwards yet?

### ISSUE THREAD

**Issue by yijing2050** [SiyuanHuang95/Livox-Localization#4]
I have used the output of the livox_mapping, which is stored in  /home/yijing/rosws3/src/startup/data/lio_livox_slam.txt and /home/yijing/rosws3/src/startup/data/PCD/scans_lc_park.pcd, the modified  file_path = "/home/yijing/rosws3/src/startup/data" in global_localization.py, then I launched the file by roslaunch livox_localization localization_horizon.launch map:="/home/yijing/rosws3/src/startup/data/scancontext/PCD/scans_lc_park.pcd", then below was the output:
process[laserMapping-1]: started with pid [6317]
process[global_localization-2]: started with pid [6318]
process[transform_fusion-3]: started with pid [6319]
process[map_publishe-4]: started with pid [6335]
process[rviz-5]: started with pid [6336]
[ INFO] [1647249798.080856402]: Recognized the following parameters
[ INFO] [1647249798.081835821]:  * file_name: /home/yijing/rosws3/src/startup/data/PCD/scans_lc_park.pcd
[ INFO] [1647249798.081913968]:  * interval: 5
[ INFO] [1647249798.081945420]:  * frame_id: /map
[ INFO] [1647249798.081969742]:  * topic_name: /map
[ INFO] [1647249798.081991141]:  * latch: false
Multi thread started 
p_pre->lidar_type 1
~~~~/home/yijing/rosws3/src/slam/Livox_Localization/ file opened
[INFO] [1647249798.769313, 0.000000]: Transform Fusion Node Inited...
[INFO] [1647249799.000673, 0.000000]: Localization Node Inited...
[WARN] [1647249799.005202, 0.000000]: Waiting for global map......
[ INFO] [1647249818.279778577]: Loaded pointcloud with the following stats
[ INFO] [1647249818.279801678]:  * number of points: 7875638
[ INFO] [1647249818.279806518]:  * total size [bytes]: 126010208
[ INFO] [1647249818.279811704]:  * channel names: x y z intensity
theglobal map didn't com up in the localization rviz. Where did I set it wrong?

**Comment by SiyuanHuang95** [comment]
Hi, thanks for your interest.

I thought it could be that your point cloud map is too large, with about 8M points. Could you downsample it and try it again?

**Comment by yijing2050** [comment]
Thanks for your reply. The size of the pcd map is about 287 MB generated from your baidu disk file "around_park_2021-09-24-11-30-54.bag", sometimes it can come up in the rviz with adding Log files in Livox-Localization. But in most cases,it didn't .
The size of the pcd map is limited for your sorftware? If so, what is the maximum size of the pcd map?

**Comment by SiyuanHuang95** [comment]
There is no explicit limit for size, but it could affect the visualization part and downstream pipeline. 

Maybe you can modify the voxel_size parameter.

**Comment by yijing2050** [comment]
When I downsample the size of the pcd map to 33MB, the problem is the same with above. puzzled

**Comment by SiyuanHuang95** [comment]
You might debug it with some print-out in global_localization.py.

**Comment by yijing2050** [comment]
ok,thanks!

**Comment by SiyuanHuang95** [comment]
BTW, when you use some other Livox Lidar (other than Livox Horizon), remember to change parameters in  global_localization.py.

**Comment by yijing2050** [comment]
Thanks for your advice.I use the livox horizon. I modified the file_path = "/home/yijing/rosws3/src/startup/data/PCD/scans_lc_park.pcd" in global_localization.py, then the map can come up in the rviz.However,there are some other errors coming up.

process[laserMapping-1]: started with pid [19621]
process[global_localization-2]: started with pid [19622]
process[transform_fusion-3]: started with pid [19623]
process[map_publishe-4]: started with pid [19639]
process[rviz-5]: started with pid [19640]
[ INFO] [1647397677.338249271]: Recognized the following parameters
[ INFO] [1647397677.339150595]:  * file_name: /home/yijing/rosws3/src/startup/data/PCD/scans_lc_park.pcd
[ INFO] [1647397677.339179210]:  * interval: 5
[ INFO] [1647397677.339195612]:  * frame_id: /map
[ INFO] [1647397677.339211926]:  * topic_name: /map
[ INFO] [1647397677.339227862]:  * latch: false
Multi thread started 
p_pre->lidar_type 1
~~~~/home/yijing/rosws3/src/slam/Livox_Localization/ file opened
[INFO] [1647397677.923341]: Transform Fusion Node Inited...
[INFO] [1647397678.190153]: Localization Node Inited...
[WARN] [1647397678.193358]: Waiting for global map......
[ INFO] [1647397698.208271421]: Loaded pointcloud with the following stats
[ INFO] [1647397698.208292887]:  * number of points: 7875638
[ INFO] [1647397698.208298720]:  * total size [bytes]: 126010208
[ INFO] [1647397698.208304045]:  * channel names: x y z intensity
[INFO] [1647397703.736406]: Global map received.
Traceback (most recent call last):
  File "/home/yijing/rosws3/src/slam/Livox_Localization/scripts/global_localization.py", line 260, in <module>
    livox_sc.livox_load_sc_rk()
  File "/home/yijing/rosws3/src/slam/Livox_Localization/scripts/scan_context_manager.py", line 155, in livox_load_sc_rk
    self.load_sc(sc_path)
  File "/home/yijing/rosws3/src/slam/Livox_Localization/scripts/scan_context_manager.py", line 227, in load_sc
    sc_files = os.listdir(sc_file_path)
OSError: [Errno 20] Not a directory: '/home/yijing/rosws3/src/startup/data/PCD/scans_lc_park.pcd/scancontext'
[global_localization-2] process has died [pid 19622, exit code 1, cmd /home/yijing/rosws3/src/slam/Livox_Localization/scripts/global_localization.py __name:=global_localization __log:=/home/yijing/.ros/log/afcb4932-a4cb-11ec-80de-28d0ea7fbc32/global_localization-2.log].
log file: /home/yijing/.ros/log/afcb4932-a4cb-11ec-80de-28d0ea7fbc32/global_localization-2*.log
[ INFO] [1647398103.182847916]: IMU Initial Done
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
[ WARN] [1647398435.547960775]: imu loop back, clear buffer
[ERROR] [1647398435.550841973]: lidar loop back, clear buffer

**Comment by SiyuanHuang95** [comment]
From your terminal:

OSError: [Errno 20] Not a directory:
'/home/yijing/rosws3/src/startup/data/PCD/scans_lc_park.pcd/scancontext'


Please check your file existence.

Best

yijing2050 ***@***.***> 于2022年3月16日周三 11:00写道：

**Comment by SiyuanHuang95** [comment]
Since no update anymore, I will close this issue
