### ISSUE TITLE
作者您好，有个问题想请教一下

### ISSUE THREAD

**Issue by znzouxiaqu** [SiyuanHuang95/Livox-Localization#6]
我在livox_mapping里保存了txt文件，里面有历史位姿数据，但是这个txt，不是**.odom格式，所以想问一下：
1，***.odom文件是怎么来的，或者说怎么生成？
2，最后生成的***.odom文件是一个？还是很多个，且数量和历史关键帧数量一样多？
3，另外一个问题，我改了livox_mapping代码，生成的一帧一帧的pcd有2722个，但是位姿txt里的数据有2723行，多了一行，这个就对应不上了，不知道是什么问题，用的你公开的bag包是around_park_2021-09-24-11-36-03.bag

**Comment by SiyuanHuang95** [comment]
1. *.odom 主要是为了和interactive_slam对齐
2. 多个文件，每一个keyframe有一个
3. 你可以对应着查一下时间戳信息

**Comment by znzouxiaqu** [comment]
> 1. *.odom 主要是为了和interactive_slam对齐
> 2. 多个文件，每一个keyframe有一个
> 3. 你可以对应着查一下时间戳信息

可以，已经跑通了，用你的python程序，生成了你百度网盘里的sc文件，修改了一些python相关的接口和几个变量名称，现在已经可以将你的几个开源数据包建图后，再定位。目前唯一的一个问题在rviz中，display面板里/path那里显示是红的有错误，不知道是话题生成错误还是什么问题，还得再看看

**Comment by SiyuanHuang95** [comment]
好的，希望我们的项目能对你有所帮助！

rviz的可视化基本无伤大雅，可以看看是否是base_frame的选择问题。

祝顺利
