### ISSUE TITLE
重定位时起始点找不准的问题

### ISSUE THREAD

**Issue by greatplan2017** [SiyuanHuang95/Livox-Localization#7]
您好。我们自己录制的rosbag播放从头开始播放，重定位效果很好。但是当我们把rosbag包跳过开头，比如说100秒处开始播放，重定位就没法找到相应的位置，请问是怎么回事？

**Comment by SiyuanHuang95** [comment]
您好，使用ScanContext的前提是场景有较好差异性，这是ScanContext的局限性；同时，使用Horizon，FOV比较小，很难编码充足的信息。

重定位是SLAM里面最难得topic，ScanContext作为经典的算法，的确不能很好解决。

**Comment by greatplan2017** [comment]
您有尝试过其他鲁棒性更好的重定位算法吗?

**Comment by SiyuanHuang95** [comment]
重定位本来就是有点病态的问题，比较难解。

欢迎你尝试后进行PR

**Comment by SiyuanHuang95** [comment]
Since no update, I will close this issue. You are welcome to re-open it when there is any update.

**Comment by greatplan2017** [comment]
我增加了GPS进行初始化定位，比原效果会更好一些。

**Comment by SiyuanHuang95** [comment]
GPS的确能提供比较好的初始化信息，感谢同步

**Comment by valenbase** [comment]
Are there some differences between starting from the beginning of the bag or the middle time of the bag for global localization?

**Comment by qimao7213** [comment]
你好，ScanContext是绕着lidar水平360扫一圈，但是livox avia的前向扫描，这种情况下的ScanContext是如何实现的呢？

**Comment by SiyuanHuang95** [comment]
> 你好，ScanContext是绕着lidar水平360扫一圈，但是livox avia的前向扫描，这种情况下的ScanContext是如何实现的呢？

@qimao7213 我们按照FoV扣出来的；其他位置应该是置0
